@startuml Bezique

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "CSharp"

[RenderConfig.CSharp]
NameSpace = "BeziqueCore;"
'/

hide empty description
skinparam stateMessageAlignment center

state StartGame

[*] --> StartGame
StartGame --> DealTwoPlayer : TwoPlayerGame
StartGame --> DealFourPlayer : FourPlayerGame

state DealTwoPlayer{
    state Deal2_FirstPlayer
    state Deal2_SecondPlayer
    
    [*] -down-> Deal2_FirstPlayer 
    Deal2_FirstPlayer --> Deal2_SecondPlayer : Complete
    Deal2_SecondPlayer --> Deal2_FirstPlayer : DealNotComplete
    Deal2_SecondPlayer --> FlipTrump : DealComplete
    
    Deal2_FirstPlayer : enter / _adapter.DealThreeCards();
    Deal2_SecondPlayer : enter / _adapter.DealThreeCards();
    
}

state DealFourPlayer{
    state Deal4_FirstPlayer
    state Deal4_SecondPlayer
    state Deal4_ThirdPlayer
    state Deal4_FourthPlayer
    
    [*] -down-> Deal4_FirstPlayer 
    Deal4_FirstPlayer --> Deal4_SecondPlayer : Complete
    Deal4_SecondPlayer --> Deal4_ThirdPlayer : Complete
    Deal4_ThirdPlayer --> Deal4_FourthPlayer : Complete
    Deal4_FourthPlayer --> Deal4_FirstPlayer : DealNotComplete
    Deal4_FourthPlayer --> FlipTrump : DealComplete
    
    Deal4_FirstPlayer : enter / _adapter.DealThreeCards();
    Deal4_SecondPlayer : enter / _adapter.DealThreeCards();
    Deal4_ThirdPlayer : enter / _adapter.DealThreeCards();
    Deal4_FourthPlayer : enter / _adapter.DealThreeCards();
}



state FlipTrump

FlipTrump : enter / _adapter.FlipCard();

FlipTrump --> Add10PointsToDealer : Trump7
FlipTrump --> PlayPhase1 : OtherCard

Add10PointsToDealer : enter / _adapter.Add10PointsToDealer();

Add10PointsToDealer --> PlayPhase1 : Complete



state PlayPhase1{
    state Phase1_TrickStart
    state Phase1_Wait
    state Phase1_Play
    state Phase1_TrickWinner
    
    [*] --> Phase1_TrickStart
    Phase1_TrickStart --> Phase1_Wait :OpponentTurn
    Phase1_TrickStart --> Phase1_Play :PlayerTurn
    
    Phase1_Wait --> Phase1_Play : OpponentPlayed
    Phase1_Play --> Phase1_Wait : WaitingForOpponent
    
    Phase1_Wait : enter / _adapter.AllPlayerPlayed();
    Phase1_Play : enter / _adapter.AllPlayerPlayed();
    
    Phase1_Wait --> Phase1_TrickWinner : AllPlayerPlayed
    Phase1_Play --> Phase1_TrickWinner : AllPlayerPlayed
    
    Phase1_TrickWinner : enter / _adapter.DetermineWinner();
    
    Phase1_TrickWinner --> Meld : MeldOpportunity
    Phase1_TrickWinner --> DrawACard : NoMeldOpportunity
    
    Meld : enter / _adapter.AddMeldPoint();
    
    Meld --> DrawACard : MeldPointGiven
    DrawACard --> DrawACard : MorePlayersToDraw
    DrawACard --> Deck : DrawCardToAll
    
    DrawACard : enter / _adapter.DrawCardFromDeck();
    
    Deck : enter / _adapter.CheckDeckCardCount();
    
    Deck --> PlayPhase2 : DeckEmpty
    Deck --> Phase1_TrickStart : AvailableCardsOnDeck
}

state PlayPhase2{
    state Phase2_TrickStart
    
    state Phase2_Wait
    state Phase2_Play
    state Phase2_TrickWinner
    
    [*] --> Phase2_TrickStart
    Phase2_TrickStart --> Phase2_Wait :OpponentTurn
    Phase2_TrickStart --> Phase2_Play :PlayerTurn
    
    Phase2_Wait : enter / _adapter.AllPlayerPlayed();
    Phase2_Play : enter / _adapter.AllPlayerPlayed();
    
    Phase2_Wait --> Phase2_TrickWinner : AllPlayerPlayed
    Phase2_Play --> Phase2_TrickWinner : AllPlayerPlayed
    Phase2_Play --> Phase2_Wait : WaitingForOpponent
    
    Phase2_TrickWinner : enter / _adapter.DetermineWinner();
    
    Phase2_TrickWinner --> Hand 
    
    Hand : enter / _adapter.CheckCardsOnHand();
        
    Hand --> RoundEnd : HandEmpty
    Hand --> Phase2_TrickStart : MoreCardsInHand
    
    
    
}

RoundEnd --> GameEnd : WinningScore


RoundEnd --> StartGame : WinningScoreNotReached



@enduml
